Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -9,26 +9,24 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-20.04
-    strategy:
-      matrix:
-        java: [ '8', '11', '13', '15' ]
-    name: Java ${{ matrix.Java }} sample
+
+    runs-on: ubuntu-latest
+
     steps:
-      - uses: actions/checkout@v3
-      - name: Setup java
-        uses: actions/setup-java@v3
-        with:
-          distribution: '<distribution>'
-          java-version: ${{ matrix.java }}
-      - run: java -cp java HelloWorldApp
-      - name: Build with Maven
-        working-directory: ./UI_Automation
-        run: mvn test --file pom.xml
+    - uses: actions/checkout@v3
+    - name: Set up JDK 11
+      uses: actions/setup-java@v3
+      with:
+        java-version: '11'
+        distribution: 'temurin'
+        cache: maven
+    - name: Build with Maven
+      working-directory: ./UI_Automation
+      run: mvn test --file pom.xml
       
-      - uses: actions/upload-artifact@v3     # upload test results
-        if: success() || failure()           # run this step even if previous step failed
-        with:
-         name: test result
-         path: |
+    - uses: actions/upload-artifact@v3     # upload test results
+      if: success() || failure()           # run this step even if previous step failed
+      with:
+        name: test result
+        path: |
           target/surefire-reports/
