Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -1,21 +1,32 @@
+# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
+# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
+
 name: Java CI with Maven
+
 on:
- workflow_dispatch:
- push:
-    branches: [ master ]
- pull_request:
- 
-    branches: [ master ]
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
+
 jobs:
   build:
+
     runs-on: ubuntu-latest
+
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v3
     - name: Set up JDK 15
-      uses: actions/setup-java@v2
+      uses: actions/setup-java@v3
       with:
-       java-version: '15'
-       distribution: 'adopt'
+        java-version: '15'
+        distribution: 'temurin'
+        cache: maven
     - name: Build with Maven
       working-directory: ./UI_Automation
-      run: mvn clean test
+      run: mvn test --file pom.xml
+      
+    - uses: actions/upload-artifact@v3     # upload test results
+      if: success() || failure()           # run this step even if previous step failed
+      with:
+        name: test result
+        path: |
+          target/surefire-reports/
